version: "3"
services:
  app:
    container_name: hatena-intern-diary-app
    build: .
    image: perl-intern-diary
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      PORT: 3000
      ORIGIN: http://localhost:3000
      DATABASE_HOST: db
      DATABASE_NAME: intern_diary
#     env_file: .env
    working_dir: /app
    links:
      - db
    tty: true
    stdin_open: true
    command: ["./script/appup"]
  db:
    container_name: hatena-intern-diary-db
    image: mysql:5.7
    volumes:
      - ./db/docker:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
