version: "3"
services:
  app:
    build: .
    image: perl-intern-bookmark
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app/
    environment:
      PORT: 3000
      ORIGIN: http://localhost:3000
      DATABASE_HOST: db
      DATABASE_NAME: intern_bookmark
    env_file: .env
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - ./db/docker:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
